apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
   mysql-root-password: cm9vdAo=
   mysql-database: bXlkYXRhYmFzZQo=
   mysql-user: cm9vdAo=
   mysql-password: cm9vdAo=