apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-cm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:    # pod template
    metadata:
      labels:
        component: mysql
    spec:     
      initContainers:
        - name: init-mysql
          image: mysql
          command:
            - bash 
            - "-c"
            - | 
              cp /tmp/vgeorga/test/my.cnf /etc/mysql/conf.d/
          volumeMounts:
            - name: mysql-config-map
              mountPath: /tmp/vgeorga/test
            - name: conf
              mountPath: /etc/mysql/conf.d
      containers:   # container specification
        - name: mysql 
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-config-map
              mountPath: /tmp/vgeorga/test
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql-data-backup
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpass
                  key: MYSQL_ROOT_PASSWORD # secret created using > kubectl create secret generic mysqlpass --from-literal MYSQL_ROOT_PASSWORD='r00t!@#$'
            - name: MYSQL_DATABASE
              value: "TEST"
      volumes:
        - name: mysql-config-map
          configMap:
            name: mysql-demo-config  # value from .medata.name of the myqsl-configmap.yaml file
            items:
              - key: my.cnf
                path: my.cnf
        - name: conf
          emptyDir: {}
        - name: mysql-data-backup
          persistentVolumeClaim:
            claimName: mysql-pvc # mysql-pv-claim # 